name: finsnap
description: "Offline-first personal finance management app with OCR and AI features"
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Database
  drift: ^2.20.3
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0

  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0
  json_annotation: ^4.9.0

  # Image Processing & OCR
  image_picker: ^1.1.2
  image: ^4.2.0
  camera: ^0.11.0+2

  # Notifications
  flutter_local_notifications: ^17.2.3
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0

  # Charts & Reports
  fl_chart: ^0.69.2
  syncfusion_flutter_charts: ^27.1.58
  syncfusion_flutter_xlsio: ^27.1.58

  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  permission_handler: ^11.3.1
  share_plus: ^10.1.1
  url_launcher: ^6.3.1
  timezone: ^0.9.4

  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  drift_dev: ^2.20.3
  json_serializable: ^6.8.0
  
  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
