name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Run code generation
      run: dart run build_runner build --delete-conflicting-outputs
      
    - name: Verify formatting
      run: dart format --output=none
      
    - name: Analyze code
      run: flutter analyze
      
    - name: Run tests
      run: flutter test --coverage
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/lcov.info
        
  build-web:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Run code generation
      run: dart run build_runner build --delete-conflicting-outputs
      
    - name: Build web
      run: |
        flutter build web --release \
          --dart-define=API_BASE_URL="${{ secrets.API_BASE_URL || 'https://golddrop.ir' }}" \
          --dart-define=BACKEND_API_KEY="${{ secrets.BACKEND_API_KEY }}" \
          --dart-define=APP_NAME="FinSnap" \
          --dart-define=SEND_RECEIPTS_TO_CLOUD=true \
          --dart-define=DEFAULT_CURRENCY=IRR \
          --dart-define=PUSH_ENABLED=true
          
    - name: Upload web build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: build/web/
        retention-days: 30
        
  build-android:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Run code generation
      run: dart run build_runner build --delete-conflicting-outputs
      
    - name: Build Android APK
      run: |
        flutter build apk --release \
          --dart-define=API_BASE_URL="${{ secrets.API_BASE_URL || 'https://golddrop.ir' }}" \
          --dart-define=BACKEND_API_KEY="${{ secrets.BACKEND_API_KEY }}" \
          --dart-define=APP_NAME="FinSnap" \
          --dart-define=SEND_RECEIPTS_TO_CLOUD=true \
          --dart-define=DEFAULT_CURRENCY=IRR \
          --dart-define=PUSH_ENABLED=true
          
    - name: Upload Android APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/
        retention-days: 30
